# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  setup:
    cmds:
      - docker pull ghcr.io/esphome/esphome

  flash:serial:
    cmds:
      - docker compose run --rm esphome run eink.yaml --device /dev/ttyACM0
  
  flash:
    cmds:
      - docker compose run --rm esphome run eink.yaml --device eink.local
  
  compile:
    cmds:
      - docker compose run --rm esphome compile eink.yaml

  run:
    cmds:
      - task: compile
      - task: flash:serial
  
  logs:
    cmds:
      - docker compose run --rm esphome logs eink.yaml --device eink.local

  logs:serial:
    cmds:
      - docker compose run --rm esphome logs eink.yaml --device /dev/ttyACM0
