esphome:
  name: ${node_name}
  friendly_name: ${node_friendly_name}
  #build_path: ../../build/${node_name}
  on_boot:
    priority: -100.0
    then:
      - logger.log: "${node_name} started"

preferences:
  flash_write_interval: 2min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 120min
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${node_name}
    password: !secret ap_password

# captive_portal:

improv_serial:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API and define services
api:
  #encryption:
  #  key: !secret api_key
  #reboot_timeout: 120min

ota:
  - platform: esphome
  #password: !secret ota_password

button:
  - platform: restart
    name: Restart

sensor:
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 15s
  - platform: uptime
    name: Uptime Sensor
    update_interval: 60s
