# Uncomment lines below if you have problems with $PATH
#SHELL := /bin/bash
#PATH := /usr/local/bin:$(PATH)

all:
	pio run

upload:
	pio run --target upload

clean:
	pio run --target clean

update:
	pio pkg update
